src/main/java/com/algorand/algosdk/account/Account.java

Prefer using `new Account(seed)` instead.
This is backwards compatible, we can bump the version at a later time. Previously, the constructor would throw an exception in all use cases.

remove unused (and thoroughly broken) Account(sk,pk) constructor

---

WORKSPACE

* Update bazel_common to the latest commit in master as today

Fix for 'depset' is not iterable build error

---

CHANGELOG.md
README.md
src/main/java/com/algorand/algosdk/mnemonic/Wordlist.java

-- This is an important fix. 
Apparently, there was a typo in one of the Mnemonic words. Luckily, the fix is simple and there are no severe consequences. When one upgrades to this patch, there is a need to let the users know that if they have the word "setupIfNeeded" in their passphrase, they should change it to "setup". Everything else remains the same and it doesn't affect their private keys.

[Important] - Change the word setupIfNeeded to setup

---

src/main/java/com/algorand/algosdk/account/Account.java

Previous PR removed this method. This PR adds it back but deprecated.
Reword setFeeByFeePerByte comments.

Restore and deprecate transactionWithSuggestedFeePerByte

---

src/main/java/com/algorand/algosdk/account/Account.java
src/main/java/com/algorand/algosdk/templates/DynamicFee.java
src/test/java/com/algorand/algosdk/templates/TestTemplates.java

Implementation of the DynamicFee template. This code has a workaround for the inconsistent fee initialization in order for the golden to match those used by the other SDKs. A followup PR will be made to fix the fee initialization issue because those changes will break many of the existing unit tests.

DynamicFee Template

---

src/main/java/com/algorand/algosdk/account/Account.java
src/main/java/com/algorand/algosdk/auction/Bid.java
src/main/java/com/algorand/algosdk/crypto/Address.java
src/main/java/com/algorand/algosdk/crypto/Digest.java
src/main/java/com/algorand/algosdk/crypto/Ed25519PublicKey.java
src/main/java/com/algorand/algosdk/crypto/MultisigAddress.java
src/main/java/com/algorand/algosdk/crypto/ParticipationPublicKey.java
src/main/java/com/algorand/algosdk/crypto/VRFPublicKey.java
src/main/java/com/algorand/algosdk/logic/Logic.java
src/main/java/com/algorand/algosdk/templates/ContractTemplate.java
src/main/java/com/algorand/algosdk/templates/DynamicFee.java
src/main/java/com/algorand/algosdk/transaction/Transaction.java
src/main/java/com/algorand/algosdk/transaction/TxGroup.java
src/main/java/com/algorand/algosdk/util/AlgoConverter.java
src/main/java/com/algorand/algosdk/util/Encoder.java
src/test/java/com/algorand/algosdk/account/TestAccount.java
src/test/java/com/algorand/algosdk/crypto/TestLogicsigSignature.java
src/test/java/com/algorand/algosdk/crypto/TestMultisigAddress.java
src/test/java/com/algorand/algosdk/templates/TestTemplates.java
src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
src/test/java/com/algorand/algosdk/util/TestUtil.java

Replace duplicate json encoding test methods with a single method which also tests the msgpack encoding.
Fix a bug that was uncovered by these tests.

Remove duplicate 'jsonSerializeDeserializeCheck' methods

---

README.md
pom.xml
src/test/java/com/algorand/algosdk/account/TestAccount.java
src/test/java/com/algorand/algosdk/crypto/TestAddress.java
src/test/java/com/algorand/algosdk/crypto/TestLogicsigSignature.java
src/test/java/com/algorand/algosdk/crypto/TestMultisigAddress.java
src/test/java/com/algorand/algosdk/logic/TestLogic.java
src/test/java/com/algorand/algosdk/mnemonic/TestMnemonic.java
src/test/java/com/algorand/algosdk/templates/TestTemplates.java
src/test/java/com/algorand/algosdk/transaction/TestTransaction.java

This required some build magic to make tests using Java 8, which is required by JUnit5. This has the added benefit of allowing us to use more expressive assertions for exception validation.
It seems to work alright with IntelliJ, but the IDE will think that lambda's are OK, which definitely isn't the case. Anything outside the IDE will properly set the build target, and will fail to compile Java 8 features (assuming they aren't cached, so `mvn clean package` may need to be done).

Use JUnit5.

---

src/main/java/com/algorand/algosdk/transaction/Transaction.java
src/test/java/com/algorand/algosdk/transaction/TestTransaction.java

It was possible to put the note/lease fields into an invalid state, added some additional checks.

Make sure note and lease can't be set to an empty byte array.

---

Dockerfile
run_integration_tests.sh
src/test/java/com/algorand/algosdk/integration/Stepdefs.java

Support for the new cucumber with indexer environment.
Changes:
1. Connection information is now static, update SDK to use hard coded token + ports.
2. Docker container only needs to build + run the SDK, so it is greatly simplified (and can leverage an off the shelf container if one exists).
3. The driver script stays mostly the same, but now calls `./scripts/up.sh` to start the test environment, and launches its own container with `--network host` so that it can use `localhost:<port>` in the tests.

Update Java SDK for indexer integration testing.

---

Makefile
src/test/java/com/algorand/algosdk/integration/Stepdefs.java

The step which sets the account back to the original auth address was missing, this fixes the run-order issue.

Finish the rekey integration test and remove the run-order requirement.

---

generator/src/main/java/com/algorand/sdkutils/Main.java
generator/src/main/java/com/algorand/sdkutils/RunAlgodV2Generator.java
generator/src/main/java/com/algorand/sdkutils/RunIndexerGenerator.java
generator/src/main/java/com/algorand/sdkutils/generators/Generator.java
generator/src/main/java/com/algorand/sdkutils/generators/QueryMapperGenerator.java
generator/src/main/java/com/algorand/sdkutils/generators/TemplateGenerator.java
generator/src/main/java/com/algorand/sdkutils/generators/TestGenerator.java
generator/src/main/java/com/algorand/sdkutils/listeners/GoGenerator.java
generator/src/main/java/com/algorand/sdkutils/listeners/Publisher.java
generator/src/main/java/com/algorand/sdkutils/listeners/Subscriber.java
generator/src/main/java/com/algorand/sdkutils/utils/StructDef.java
generator/src/main/java/com/algorand/sdkutils/utils/Tools.java
generator/src/main/java/com/algorand/sdkutils/utils/TypeDef.java

In this change, the generator is enhanced to be a general purpose
generator.
Publisher/Subscriber paradigm is added to build generators outside the
spec file parser.
Relevant events such as new model or new parameter, with the relevant
customizations, e.g. type conversion are published, and subscribers
can pick up the messages and generate code.
The first use case of the publisher/subscriber is implemented for
generating go-sdk code.

Generator enhancements and go-sdk generator 

---

generator/src/main/java/com/algorand/sdkutils/generators/Generator.java
generator/src/main/java/com/algorand/sdkutils/listeners/GoGenerator.java
generator/src/main/java/com/algorand/sdkutils/utils/Tools.java

* Make go-lint compatible comments, Java should be affected.
* Pass request method to Do generator
Examples of new style comments in go:
```
// Account information at a given round.
// Definition:
// data/basics/userBalance.go : AccountData
type Account struct {
```
```
// Metrics /metrics
type Metrics struct {
c *Client
}
// Do performs HTTP request
func (s *Metrics) Do(ctx context.Context,
```

Improve go generator

---

generator/pom.xml
generator/src/main/java/com/algorand/sdkutils/Generate.java
generator/src/main/java/com/algorand/sdkutils/Main.java
generator/src/main/java/com/algorand/sdkutils/RunAlgodV2Generator.java
generator/src/main/java/com/algorand/sdkutils/RunIndexerGenerator.java
generator/src/main/java/com/algorand/sdkutils/generators/OpenApiParser.java
generator/src/main/java/com/algorand/sdkutils/generators/QueryMapperGenerator.java
generator/src/main/java/com/algorand/sdkutils/generators/ResponseGenerator.java
generator/src/main/java/com/algorand/sdkutils/generators/TemplateGenerator.java
generator/src/main/java/com/algorand/sdkutils/generators/TestGenerator.java
generator/src/main/java/com/algorand/sdkutils/listeners/GoGenerator.java
generator/src/main/java/com/algorand/sdkutils/listeners/Publisher.java
generator/src/main/java/com/algorand/sdkutils/utils/StructDef.java
generator/src/main/java/com/algorand/sdkutils/utils/TypeDef.java
run_generator.sh

* `Generator` -> `OpenApiParser`
* `legacyMode` flag in `OpenApiParser` so that the parser can run without supplying java configurations.
* `parse()` function in `OpenApiParser` to more intuitively run the operations done by the static `Generate` method (and only the required operations).
* Improved CLI parsing to allow multiple subcommands.
* Stubbed in `responses` subcommand.

Generator refactoring.

---

generator/src/main/java/com/algorand/sdkutils/RunAlgodV2AndIndexerGenerators.java
generator/src/main/java/com/algorand/sdkutils/generators/OpenApiParser.java
generator/src/main/java/com/algorand/sdkutils/listeners/GoGenerator.java

* Parser support for Optional list of classes: only the listed classes are processed.
This is useful when generated code will co-exist with hand written one.
e.g. generating only application models for go.
* Fixed response type missing documentation.
* Optional name for go models file name (default: responsemodels.go)
* Enhanced main method for passing different args.
* Some go fixes (SignedTransaction, Account)

Generator features and go enhancements

---

generator/src/main/java/com/algorand/sdkutils/generators/OpenApiParser.java
generator/src/main/java/com/algorand/sdkutils/listeners/GoGenerator.java
generator/src/main/java/com/algorand/sdkutils/listeners/JavaGenerator.java
src/main/java/com/algorand/algosdk/v2/client/model/ApplicationParams.java
src/main/java/com/algorand/algosdk/v2/client/model/BlockResponse.java
src/main/java/com/algorand/algosdk/v2/client/model/TransactionApplication.java

1. Correct array of byte array type. It is used by application-args.
2. Fix for conflicting alias type classes 
No file should be generated when the type is an alias.
There are some alias types in one spec file, which
are in contradiction with real types in the other spec file.
We don't want the alias type file to corrupt the real type object.

correct array of byte arrays used by application-args.

---

src/main/java/com/algorand/algosdk/v2/client/common/AlgodClient.java
src/main/java/com/algorand/algosdk/v2/client/common/IndexerClient.java

Added new constructors to algodv2 and indexer classes that allows for a custom token key.
This allows connecting to APIs that use a different token keys from the default ones.
Given that the common Client class already allows this, the new constructors just calls super with the received parameters.

New constructors for v2 and Indexer that also accepts tokenKey

---

src/main/java/com/algorand/algosdk/v2/client/common/PathResponse.java

It is difficult to interpret and read the stringified json output of Objects extending the PathResponse class as the output appears in a single line and is not formatted.
Added the option to use default pretty printer to the object mapper instance so that the outputs appear as formatted json strings.

Added pretty print option to Object Mapper instance

---

src/main/java/com/algorand/algosdk/transaction/AssetParams.java
src/test/java/com/algorand/algosdk/transaction/TestTransaction.java

https://github.com/algorand/java-algorand-sdk/pull/74
prevents non-base64 strings to be metadatahash
However, the specs of Algorand allows for metadatahash to be any
array of 32 bytes. This is important to allow to store SHA256 hashes
for example. Indeed, a 32-byte base64 string only represents 24 bytes.
This commit fixes the above and adds tests to check that all the ways
to provide metadata hash (as a UTF8 string, as a base64 string, or
as a byte array) leads to the same transaction.
Furthermore, this commit ensures that metadatahash is exactly 32
bytes, as mandated by the spec.
See
https://github.com/algorandfoundation/specs/blob/master/dev/ledger.md#assets
and
https://github.com/algorand/go-algorand/blob/96b16ff090014e520a4695285d4167d26c5468ad/data/basics/userBalance.go#L364

Allow non-base64 metadatahash and force 32 bytes

---

src/main/java/com/algorand/algosdk/transaction/AtomicTransactionComposer.java

Add specific error message obtained by rPost transaction when It tried to submit an atomic transaction composer and It failed

add error message with atomic transaction composer

---

.github/workflows/codegen.yml

Adds a github workflow which will call our code gen action.  
Depends on action being defined in  our generator... See https://github.com/algorand/generator/pull/32 for more details and testing done.
Runs on a cron job daily at 23:20. The Github docs say to try to avoid common times because there will be natural spikes of event processing happening then, so I've defined all of the jobs at an arbitrary time during the night.
It will run the code generator, commit to a branch if necessary, and open a PR for us to review. It will no-op if the branch w/ identical changes already exist.

Build: Add SDK code generation workflow

---

.github/workflows/codegen.yml

Github is complaining that I've left out the "version" which is supposed to be the branch we are referencing a remote action from. Added that in their builtin editor and it seems to be happy with the workflow definition now.

Add branch info to sdk gen action

---

src/main/java/com/algorand/algosdk/transaction/AtomicTransactionComposer.java
src/test/java/com/algorand/algosdk/integration/AtomicTxnComposer.java

Adds the method obj in the Return obj for abi contract calls

adding method to abi result object

---

.gitignore

Ignores copied over txt test resource files to prevent incidental versioning.
Without the change, running `make test` produces these untracked changes:
```
➤ Untracked files
#
#
```
The .txt files in-question stem from https://github.com/algorand/algorand-sdk-testing/pull/161.

Ignore copied over txt test resource files

---

src/main/java/com/algorand/algosdk/logic/Logic.java
src/test/java/com/algorand/algosdk/logic/TestLogic.java

This PR adds additional version consolidation changes to [the existing TEAL/AVM language consolidation PR](https://github.com/algorand/java-algorand-sdk/pull/348).

AVM: AVM/TEAL version consolidation additions

---

src/main/java/com/algorand/algosdk/logic/Logic.java
src/test/java/com/algorand/algosdk/logic/TestLogic.java

Applies feedback from https://github.com/algorand/go-algorand/issues/4125 to consolidate TEAL and AVM versions.

AVM:  Consolidate TEAL and AVM versions

---

Makefile
run_integration_tests.sh
src/test/java/com/algorand/algosdk/integration/Applications.java
src/test/java/com/algorand/algosdk/integration/Stepdefs.java
src/test/java/com/algorand/algosdk/integration/TransientAccount.java

Implements step changes from https://github.com/algorand/algorand-sdk-testing/pull/206/ and https://github.com/algorand/algorand-sdk-testing/pull/212/ to support integration testing with dev mode network.  The motivation is to speed up test execution time.  
Notes:
* Analogous to https://github.com/algorand/py-algorand-sdk/pull/360.  Like https://github.com/algorand/py-algorand-sdk/pull/360, the PR advances rounds by submitting a transaction from an isolated account.
* Limits `make integration` to running integration tests.  Previously, the target re-ran unit tests.

Testing: Modify cucumber steps to use dev mode network 

---

.github/release.yml
.github/workflows/pr-type-category.yml
.gitignore
CHANGELOG.md
Makefile
README.md
pom.xml
src/main/java/com/algorand/algosdk/logic/Logic.java
src/main/java/com/algorand/algosdk/logic/SourceMap.java
src/main/java/com/algorand/algosdk/v2/client/model/Enums.java
src/test/java/com/algorand/algosdk/integration/Applications.java
src/test/java/com/algorand/algosdk/integration/Stepdefs.java
src/test/java/com/algorand/algosdk/integration/TransientAccount.java
src/test/java/com/algorand/algosdk/logic/TestLogic.java
src/test/java/com/algorand/algosdk/unit/TestSourceMap.java
src/test/java/com/algorand/algosdk/util/TestEncoder.java

* DevTools: adding source map decoder by @barnjamin in https://github.com/algorand/java-algorand-sdk/pull/352
* Github-Actions: Adding pr title and label checks by @algojack in https://github.com/algorand/java-algorand-sdk/pull/339
* Enhancement: Add UNKNOWN enum type to HTTP client enums. by @winder in https://github.com/algorand/java-algorand-sdk/pull/351
* AVM:  Consolidate TEAL and AVM versions by @michaeldiamant in https://github.com/algorand/java-algorand-sdk/pull/348
* Testing: Modify cucumber steps to use dev mode network  by @michaeldiamant in https://github.com/algorand/java-algorand-sdk/pull/350
* Ignore copied over txt test resource files by @michaeldiamant in https://github.com/algorand/java-algorand-sdk/pull/342
**Full Changelog**: …

FOR REVIEW ONLY - java-algorand-sdk v1.17.0

---

test-harness.sh

Following up from the companion [SDK Testing Bugfix PR](https://github.com/algorand/algorand-sdk-testing/pull/224), we're going to pass through verbosity to the harness script via a new `-v` flag.
For further context: here is what [SDK Testing Bugfix PR](https://github.com/algorand/algorand-sdk-testing/pull/224) says:
> The sandbox is always defaulting to `release` and the generated `config.harness` isn't sticking because the verbose flag is provided in the wrong order. 
> 
> Additionally, after refactoring the SDK Sandboxization PR's to no longer overwrite `.env`, there is no way to pass through the verbosity, except by overwriting. The PR re-enables passing through by also reading `VERBOSE_HARNESS` as a flag (either `-v` or `--verbose`).

Bug-Fix: Pass verbosity to the harness and sandbox

---

src/main/java/com/algorand/algosdk/transaction/Transaction.java

Addresses https://github.com/algorand/java-algorand-sdk/pull/345#discussion_r976865846 by removing breaking changes to `Transaction` public constructor.
Since serialization relies on runtime annotation inspection, the PR must preserve box reference as a private constructor parameter.

Remove boxReferences from public Transaction constructor

---

src/main/java/com/algorand/algosdk/transaction/Transaction.java

Addresses https://github.com/algorand/java-algorand-sdk/pull/345#discussion_r976868216 by adding `boxReference` to `Transaction.equals`.

Add boxReference to Transaction.equals

---

src/main/java/com/algorand/algosdk/builder/transaction/MethodCallTransactionBuilder.java
src/main/java/com/algorand/algosdk/transaction/MethodCallParams.java

Reworks `MethodCallParams` to be backwards compatible with Boxes by making a protected constructor available to the builder.  Additionally, deprecates the public constructor to clearly warn about usage.

Rework MethodCallParams to be backwards compatible with Boxes

---

.test-env
Makefile
src/main/java/com/algorand/algosdk/v2/client/algod/GetBlockHash.java
src/main/java/com/algorand/algosdk/v2/client/common/AlgodClient.java
src/main/java/com/algorand/algosdk/v2/client/indexer/LookupBlock.java
src/main/java/com/algorand/algosdk/v2/client/model/Block.java
src/main/java/com/algorand/algosdk/v2/client/model/BlockHashResponse.java
src/main/java/com/algorand/algosdk/v2/client/model/ParticipationUpdates.java
src/test/java/com/algorand/algosdk/unit/AlgodPaths.java
src/test/java/com/algorand/algosdk/unit/IndexerPaths.java
src/test/java/com/algorand/algosdk/unit/ResponsesShared.java
src/test/unit.tags
test-harness.sh

Add tests to generated code. See commits for the generated code vs the tests.
Tests are passing locally, CI is pending https://github.com/algorand/algorand-sdk-testing/pull/245

REST API: Add algod block hash endpoint, add indexer block header-only param.

---

.test-env
CHANGELOG.md
Makefile
README.md
pom.xml
src/main/java/com/algorand/algosdk/v2/client/algod/GetBlockHash.java
src/main/java/com/algorand/algosdk/v2/client/common/AlgodClient.java
src/main/java/com/algorand/algosdk/v2/client/indexer/LookupBlock.java
src/main/java/com/algorand/algosdk/v2/client/model/Block.java
src/main/java/com/algorand/algosdk/v2/client/model/BlockHashResponse.java
src/main/java/com/algorand/algosdk/v2/client/model/ParticipationUpdates.java
src/test/java/com/algorand/algosdk/unit/AlgodPaths.java
src/test/java/com/algorand/algosdk/unit/IndexerPaths.java
src/test/java/com/algorand/algosdk/unit/ResponsesShared.java
src/test/unit.tags
test-harness.sh

* REST API: Add algod block hash endpoint, add indexer block header-only param. by @winder in https://github.com/algorand/java-algorand-sdk/pull/413
**Full Changelog**: https://github.com/algorand/java-algorand-sdk/compare/1.19.0...1.20.0

FOR REVIEW ONLY - java-algorand-sdk 1.20.0

---

.test-env
src/main/java/com/algorand/algosdk/transaction/Transaction.java
src/test/java/com/algorand/algosdk/transaction/TestTransaction.java

This PR fixes a bug when decoding transactions with box references. This SDK should now pass the test changes from https://github.com/algorand/algorand-sdk-testing/pull/248

SDK: Fix transaction decoding with boxes

---

src/main/java/com/algorand/algosdk/abi/ABIType.java
src/test/java/com/algorand/algosdk/abi/TestTypes.java

Fix https://github.com/algorand/avm-abi/issues/12

Bug-Fix: parsing type strings for tuples containing static arrays of tuples

---

CHANGELOG.md
src/main/java/com/algorand/algosdk/transaction/TxGroup.java

While reviewing #443, I realized `assignGroupID` has been deprecated since https://github.com/algorand/java-algorand-sdk/pull/83/.  Since the method has been deprecated for > 2 years, the PR proposes removing it in v2.0.0.

Remove deprecated TxGroup.assignGroupID

---

CHANGELOG.md

See #389 and #447, some more entries in `CHANGELOG` need to be added:
- #443 
- remove v1 endpoint
- remove `MethodCallParams` public constructor
- #445 
- #442
This should be the unblocker for #447 to be merged into `develop`.

Changelog entries for breaking changes in V1 to V2

---

src/main/java/com/algorand/algosdk/crypto/LogicsigSignature.java

Adds LogicsigSignature usage disclaimer suggesting LogicSigAccount usage as a more general purpose signing mechanism.

Add LogicsigSignature usage disclaimer

---

.test-env

To improve visibility of C.I. build failures, utilize new logging capabilities in the sandbox (https://github.com/algorand/sandbox/pull/181) and set `VERBOSE_HARNESS=1`.
In particular we can now see:
* traces of the `docker compose up` command
* dumped `docker-compose logs` for:
* indexer-db
* algod
* indexer
For more information about the effects of this PR on testing in C.I. see the sibling go-sdk pr: https://github.com/algorand/go-algorand-sdk/pull/540

Enhancement: Verbose Harness

---

.circleci/config.yml
.github/workflows/create-release-pr.yml

For security purposes, we decided to swap out the changelog-builder github actions in favor of using the github release/generate-notes github api instead.
- Also updated Ubuntu CircleCI image for the integration tests.

CICD: Use release/generate-notes github api

---

.github/workflows/codegen.yml
.github/workflows/create-release-pr.yml
.github/workflows/pr-type-category.yml

- Upgrade checkout action to `v4` (`v3` is deprecated and throwing warnings)
- Check `Node.js 16` warning messages go away after next CI codegen run

ci: upgrade checkout action to v4

---

.github/workflows/ci-pr.yml
.github/workflows/pr-type-category.yml
Dockerfile
Makefile

This is an implementation of unit and integration tests in GitHub Actions.
The building of a container just to execute tests was removed from this build.
Additionally, the PR category/type check was modified to check PRs versus main instead of develop.
Verify that these and CircleCI tests still pass.

CICD: run tests in GitHub Actions

---

.github/workflows/create-release-pr.yml
.github/workflows/publish.yml
.github/workflows/release.yml
CODEOWNERS
README.md
pom.xml

With this pull request (and changes already made to the SDK's settings), the release process for the Java SDK will be as follows:
- Run create-release-pr.yml, which creates a release pull request.
- Permissioned user approves the pull request (does not merge themselves)
- Run release.yml, specifying the PR number output from (1) and the release version (tag) as inputs.
- Doublecheck releases page, proper tag created, branch, PR merged/branch deleted, etc.
As a part of this, we moved away from Git Flow to a single mainline branch (named main).

Devops: Release process update
