algorand/java-algorand-sdk

- README.md
- pom.xml
- pom_template.xml
- src/main/java/com/algorand/algosdk/algod/client/api/DefaultApi.java
- src/main/java/com/algorand/algosdk/algod/client/model/Account.java
- src/main/java/com/algorand/algosdk/algod/client/model/Block.java
- src/main/java/com/algorand/algosdk/algod/client/model/PaymentTransactionType.java
- src/main/java/com/algorand/algosdk/algod/client/model/Transaction.java
- src/main/java/com/algorand/algosdk/algod/client/model/TransactionFee.java
- src/main/java/com/algorand/algosdk/algod/client/model/TransactionParams.java
> Update model to reflect algod changes

- examples/src/main/java/com/algorand/algosdk/example/Main.java
- src/main/java/com/algorand/algosdk/account/Account.java
- src/main/java/com/algorand/algosdk/transaction/BUILD.bazel
- src/main/java/com/algorand/algosdk/transaction/Transaction.java
- src/main/java/com/algorand/algosdk/transaction/TxGroup.java
- src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
TxGroup.computeGroupID and assignGroupID
End-to-end tests agains goal clerk
> Add transaction group support

- src/main/java/com/algorand/algosdk/transaction/Transaction.java
- src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
Adding lease to java SDK transaction with test.
Also added a missing pay transaction.
> Java sdk lease

- src/main/java/com/algorand/algosdk/templates/ContractTemplate.java
- src/main/java/com/algorand/algosdk/templates/HTLC.java
- src/main/java/com/algorand/algosdk/templates/Split.java
- src/test/java/com/algorand/algosdk/templates/TestTemplates.java
ContractTemplate: main function is injecting parameter values.
HTCL and Split templates 
TestTemplates: tests both templates against the golden. HTCL is not matching the golden. Split is.
> JAVA SDK templates: HTCL and Split

- CHANGELOG.md
- README.md
- examples/pom.xml
- pom.xml
- Added support for Algorand Standardized Assets (ASA)
- Added support for Algorand Smart Contracts (ASC) 
- Added support for Hashed Time Lock Contract (HTLC) 
- Added support for Split contract
- Added support for Group Transactions
- Added support for leases
> Release 1.2.0

- examples/src/main/java/com/algorand/algosdk/example/Main.java
update one error in LogicsigTransaction
> update one error in LogicsigTransaction

- src/main/java/com/algorand/algosdk/transaction/Transaction.java
- src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
Added check for base64 encoding for asset metadataHash.
> Added check for valid Base64 encoding of asset metadataHash.

- src/main/java/com/algorand/algosdk/templates/ContractTemplate.java
- src/main/java/com/algorand/algosdk/templates/HTLC.java
- src/main/java/com/algorand/algosdk/templates/Split.java
Created a number of ParameterValue types to make the contract implementation slightly less verbose.
> Add multiple parameter value classes

- src/main/java/com/algorand/algosdk/templates/ContractTemplate.java
- src/main/java/com/algorand/algosdk/templates/DynamicFee.java
- src/main/java/com/algorand/algosdk/templates/HTLC.java
- src/main/java/com/algorand/algosdk/templates/LimitOrder.java
- src/main/java/com/algorand/algosdk/templates/PeriodicPayment.java
- src/main/java/com/algorand/algosdk/templates/Split.java
More small adjustments to this code to merge the parallel value/offset arrays
> Merge offset and parameter

- src/main/java/com/algorand/algosdk/crypto/MultisigAddress.java
- src/main/java/com/algorand/algosdk/crypto/Signature.java
- src/test/java/com/algorand/algosdk/crypto/TestLogicsigSignature.java
- src/test/java/com/algorand/algosdk/crypto/TestMultisigAddress.java
Updated unit tests to test JSON serialization for LogicSignature and MultisigAddress.  Added missing JSON annotations to MultisigAddress.
> Updated unit test to test json serialization for LogicSignature and

- src/main/java/com/algorand/algosdk/algod/client/model/AssetHolding.java
The go-algorand swagger generation is broken, so this class was not properly generated. See https://github.com/algorand/go-algorand/issues/739
Added getters and documentation.
This resolves #63
> Add missing asset holding getters.

- src/main/java/com/algorand/algosdk/builder/transaction/AssetAcceptTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetClawbackTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetConfigureTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetCreateTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetDestroyTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetFreezeTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetRevokeTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetTransferTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/KeyRegistrationTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/PaymentTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/TransactionBuilder.java
- src/main/java/com/algorand/algosdk/templates/DynamicFee.java
- src/main/java/com/algorand/algosdk/templates/HTLC.java
- src/main/java/com/algorand/algosdk/templates/LimitOrder.java
- src/main/java/com/algorand/algosdk/templates/PeriodicPayment.java
- src/main/java/com/algorand/algosdk/templates/Split.java
- src/main/java/com/algorand/algosdk/transaction/Transaction.java
- src/test/java/com/algorand/algosdk/account/TestAccount.java
- src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
Unfortunately there is a lot of boilerplate code to setup the builders the way I wanted them, but I couldn't be happier with the new developer experience when creating transactions with them.
> Create transactions with Builders.

- generator/src/main/java/com/algorand/sdkutils/generators/Generator.java
- src/main/java/com/algorand/algosdk/v2/client/algod/RawTransaction.java
- src/test/java/com/algorand/algosdk/unit/AlgodResponses.java
Generate response classes with one field.
> Generate response classes with one field.

- generator/src/main/java/com/algorand/sdkutils/generators/Generator.java
- generator/src/main/java/com/algorand/sdkutils/generators/QueryMapperGenerator.java
- src/main/java/com/algorand/algosdk/v2/client/algod/GetBlock.java
- src/main/java/com/algorand/algosdk/v2/client/algod/GetPendingTransactions.java
- src/main/java/com/algorand/algosdk/v2/client/algod/GetPendingTransactionsByAddress.java
- src/main/java/com/algorand/algosdk/v2/client/algod/PendingTransactionInformation.java
- src/main/java/com/algorand/algosdk/v2/client/algod/RawTransaction.java
- src/main/java/com/algorand/algosdk/v2/client/algod/StartCatchup.java
- src/main/java/com/algorand/algosdk/v2/client/model/BlockResponse.java
- src/main/java/com/algorand/algosdk/v2/client/model/CatchpointAbortResponse.java
- src/main/java/com/algorand/algosdk/v2/client/model/CatchpointStartResponse.java
- src/main/java/com/algorand/algosdk/v2/client/model/Enums.java
- src/test/java/com/algorand/algosdk/unit/utils/QueryMapper.java
* Stopped exposing format query parameter.
* BlockCertificate and BlockHeader are of type HashMap.
* Fixed the in-body required parameter check.
> Round of fixes for algodV2

- Makefile
- src/main/java/com/algorand/algosdk/account/Account.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetAcceptTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetClawbackTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetConfigureTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetCreateTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetDestroyTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetFreezeTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/AssetTransferTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/KeyRegistrationTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/PaymentTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/TransactionBuilder.java
- src/main/java/com/algorand/algosdk/kmd/client/model/SignTransactionRequest.java
- src/main/java/com/algorand/algosdk/transaction/SignedTransaction.java
- src/main/java/com/algorand/algosdk/transaction/Transaction.java
- src/test/java/com/algorand/algosdk/integration/RunCucumberIntegrationTest.java
- src/test/java/com/algorand/algosdk/integration/Stepdefs.java
- src/test/java/com/algorand/algosdk/unit/Rekeying.java
1. In Account class signTransaction and signMultisigTransaction
- Set authAddr to the signature account if different from the sender account
2. Add rekey method to TransactionBuilder
3. Add publicKey field to SignTransactionRequest
4. Add authAddr to SignedTransaction
5. Add rekeyTo field to Transaction
> JAVA SDK rekeying feature.

- src/main/java/com/algorand/algosdk/transaction/TxGroup.java
- src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
Throw an exception when txgroup exceeds 16 txs.
> Throw an exception when txgroup exceeds 16 txs

- src/main/java/com/algorand/algosdk/builder/transaction/TransactionBuilder.java
- src/main/java/com/algorand/algosdk/v2/client/common/Query.java
- src/main/java/com/algorand/algosdk/v2/client/common/Response.java
- src/test/java/com/algorand/algosdk/unit/utils/ClientMocker.java
The `format=msgpack` endpoints weren't working properly. Fixed the encoding step.
Also there were some missing TransactionBuilder updates.
> Fix encoder and add missing TransactionBuilder methods.

- generator/pom.xml
- generator/src/main/java/com/algorand/sdkutils/Main.java
- generator/src/main/java/com/algorand/sdkutils/generators/OpenApiParser.java
- generator/src/main/java/com/algorand/sdkutils/generators/ResponseGenerator.java
- generator/src/main/java/com/algorand/sdkutils/generators/Utils.java
- generator/src/main/java/com/algorand/sdkutils/listeners/GoGenerator.java
- generator/src/main/java/com/algorand/sdkutils/listeners/JavaGenerator.java
- generator/src/main/java/com/algorand/sdkutils/listeners/ResponseGenerator.java
- generator/src/main/java/com/algorand/sdkutils/listeners/Subscriber.java
- generator/src/main/java/com/algorand/sdkutils/utils/StructDef.java
- generator/src/main/java/com/algorand/sdkutils/utils/TypeDef.java
- generator/src/test/java/com/algorand/sdkutils/generators/OpenApiParserTest.java
- generator/src/test/resources/petstore.json
Generator command to write response files for SDK Client testing purposes.
> ResponseGenerator

- generator/src/main/java/com/algorand/sdkutils/Generate.java
- generator/src/main/java/com/algorand/sdkutils/listeners/JavaGenerator.java
When last commit added an additional parameter (models file name) to Go generator, this runner did not get updated.
> Fix  broken Generate.java

- generator/pom.xml
- generator/src/main/java/com/algorand/sdkutils/Main.java
- generator/src/main/java/com/algorand/sdkutils/generators/OpenApiParser.java
- generator/src/main/java/com/algorand/sdkutils/listeners/ResponseGenerator.java
- generator/src/main/resources/log4j2.xml
> Response generator list

- README.md
Use the Algod, kmd and Indexer clients to create a transaction on sandbox and check the result.
> Updated README example.

- src/main/java/com/algorand/algosdk/util/Encoder.java
- src/test/java/com/algorand/algosdk/util/TestEncoder.java
The base32 decode function had a bug in it. Simplify the code and add more tests.
> Fix base32 decode bug.

- src/main/java/com/algorand/algosdk/transaction/Transaction.java
- src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
Add static qualifiers to json creators for onCompletion enum serialization.
> Add static qualifiers to json creators for onCompletion enum serialization.

- src/main/java/com/algorand/algosdk/v2/client/model/Account.java
- src/main/java/com/algorand/algosdk/v2/client/model/ApplicationParams.java
- src/main/java/com/algorand/algosdk/v2/client/model/AssetParams.java
- src/main/java/com/algorand/algosdk/v2/client/model/TransactionApplication.java
Ran the code generation script to get recent REST API updates.
> Regenerate  HTTP Client (Asset b64 fields + App extra pages)

- src/main/java/com/algorand/algosdk/templates/ContractTemplate.java
- src/main/java/com/algorand/algosdk/templates/DynamicFee.java
- src/main/java/com/algorand/algosdk/templates/HTLC.java
- src/main/java/com/algorand/algosdk/templates/LimitOrder.java
- src/main/java/com/algorand/algosdk/templates/PeriodicPayment.java
- src/main/java/com/algorand/algosdk/templates/Split.java
Code to be deleted in version 2.0.0
> mark contract templates as @Deprecated

- Makefile
- src/test/java/com/algorand/algosdk/cucumber/shared/TransactionSteps.java
Implement tests from algorand/algorand-sdk-testing#145
> Add keyreg txn encoding tests

- pom.xml
Resolve #229 and #279 on upgrading jackson packages.
Close #229 and #279.
> Resolve #229 and #279 on upgrading jackson packages

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/algorand/algosdk/abi/ABIType.java
- src/main/java/com/algorand/algosdk/abi/Contract.java
- src/main/java/com/algorand/algosdk/abi/Interface.java
- src/main/java/com/algorand/algosdk/abi/Method.java
- src/main/java/com/algorand/algosdk/account/Account.java
- src/main/java/com/algorand/algosdk/transaction/AtomicTransactionComposer.java
- src/main/java/com/algorand/algosdk/transaction/MethodCallParams.java
- src/test/java/com/algorand/algosdk/abi/TestContract.java
- src/test/java/com/algorand/algosdk/abi/TestInterface.java
- src/test/java/com/algorand/algosdk/abi/TestMethod.java
- src/test/java/com/algorand/algosdk/integration/Applications.java
- src/test/java/com/algorand/algosdk/integration/AtomicTxnComposer.java
- src/test/java/com/algorand/algosdk/unit/ABIJson.java
- src/test/java/com/algorand/algosdk/unit/AtomicTxnComposer.java
- src/test/java/com/algorand/algosdk/util/SplitAndProcessABIArgs.java
Java-algorand-sdk 1.11.0-beta-2 release.
> DO NOT MERGE: Release java-algorand-sdk 1.11.0-beta-2

- CHANGELOG.md
- README.md
- pom.xml
> DO NOT MERGE: Release java-algorand-sdk 1.11.0

- CHANGELOG.md
- README.md
- pom.xml
- Add new key reg txn field (#266)
- C2C Feature and Testing (#290)
- Implement circle ci (#293)
- Update README.md (#297)
- Update langspec for teal6 (#298)
> FOR REVIEW ONLY - java-algorand-sdk 1.12.0

- CHANGELOG.md
- README.md
- pom.xml
java-algorand-sdk 1.13.0 Release
> FOR REVIEW ONLY: java-algorand-sdk 1.13.0 Release

- src/main/java/com/algorand/algosdk/v2/client/Utils.java
We should include the app address of any foreign apps passed
> adding foreign app address to dryrun creator

- src/main/java/com/algorand/algosdk/v2/client/algod/GetProof.java
- src/main/java/com/algorand/algosdk/v2/client/algod/TealDisassemble.java
- src/main/java/com/algorand/algosdk/v2/client/common/AlgodClient.java
- src/main/java/com/algorand/algosdk/v2/client/common/IndexerClient.java
- src/main/java/com/algorand/algosdk/v2/client/indexer/LookupAccountTransactions.java
- src/main/java/com/algorand/algosdk/v2/client/indexer/LookupAssetTransactions.java
- src/main/java/com/algorand/algosdk/v2/client/indexer/SearchForTransactions.java
- src/main/java/com/algorand/algosdk/v2/client/model/CompileResponse.java
- src/main/java/com/algorand/algosdk/v2/client/model/DisassembleResponse.java
- src/main/java/com/algorand/algosdk/v2/client/model/Enums.java
- src/main/java/com/algorand/algosdk/v2/client/model/ProofResponse.java
Updated the generated files using the generator commit in 
https://github.com/algorand/generator/pull/31  
and the indexer spec in https://github.com/algorand/indexer/pull/1005
> Rerun code generation based on new models

- src/main/java/com/algorand/algosdk/v2/client/model/Enums.java
- src/test/java/com/algorand/algosdk/util/TestEncoder.java
Regenerating client with changes from https://github.com/algorand/generator/pull/40
> Enhancement: Add UNKNOWN enum type to HTTP client enums.

- src/main/java/com/algorand/algosdk/builder/transaction/ApplicationBaseTransactionBuilder.java
- src/main/java/com/algorand/algosdk/builder/transaction/ApplicationCallReferencesSetter.java
- src/main/java/com/algorand/algosdk/builder/transaction/MethodCallTransactionBuilder.java
- src/main/java/com/algorand/algosdk/transaction/AppBoxReference.java
- src/main/java/com/algorand/algosdk/transaction/Transaction.java
- src/test/java/com/algorand/algosdk/integration/Applications.java
- src/test/java/com/algorand/algosdk/util/ComparableBytes.java
Child PR to #345.
This addresses most of my comments.
Still needs to be addresses:
- Addressed by #401 
- Addressed by #399
- Addressed by #399
> Box storage changes

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/algorand/algosdk/transaction/Transaction.java
- src/test/java/com/algorand/algosdk/transaction/TestTransaction.java
* SDK: Fix transaction decoding with boxes by @jasonpaulos in https://github.com/algorand/java-algorand-sdk/pull/422
**Full Changelog**: https://github.com/algorand/java-algorand-sdk/compare/1.21.0...1.21.1
> FOR REVIEW ONLY - java-algorand-sdk v1.21.1

- .test-env
- src/test/java/com/algorand/algosdk/integration/Stepdefs.java
Implements https://github.com/algorand/algorand-sdk-testing/issues/202 here
> Enhancement: Sourcemap `mapping` field deprecation

- CHANGELOG.md
- src/main/java/com/algorand/algosdk/account/Account.java
- src/main/java/com/algorand/algosdk/builder/transaction/TransactionBuilder.java
- src/main/java/com/algorand/algosdk/transaction/Transaction.java
Remove remaining deprecated methods in `Transaction`.
> Remove deprecated `setFee` and `setLease` in `Transaction`

- src/main/java/com/algorand/algosdk/transaction/MethodCallParams.java
Changing the error message to be more accurate
> Fix: improve error message for mismatched args

- src/main/java/com/algorand/algosdk/v2/client/algod/GetLedgerStateDelta.java
- src/main/java/com/algorand/algosdk/v2/client/algod/GetLedgerStateDeltaForTransactionGroup.java
- src/main/java/com/algorand/algosdk/v2/client/algod/GetTransactionGroupLedgerStateDeltasForRound.java
- src/main/java/com/algorand/algosdk/v2/client/model/TransactionAssetTransfer.java
Regenerate client for txn group deltas requests to have msgp query arg.
> algod: Regen changes for Deltas endpoints

- .test-env
- src/test/java/com/algorand/algosdk/unit/IndexerPaths.java
> bug-fix: include currency-greater-than param for 0 value

- .test-env
- src/test/java/com/algorand/algosdk/integration/Applications.java
Implements test changes from https://github.com/algorand/algorand-sdk-testing/pull/309
> Fix: Fix indexer sync issue in cucumber tests

- src/main/java/com/algorand/algosdk/v2/client/indexer/SearchForApplicationBoxes.java
- src/test/java/com/algorand/algosdk/integration/Applications.java
- src/test/java/com/algorand/algosdk/unit/utils/TestingUtils.java
Handle limit zero case in tests - the generated code should not have been manually modified.
> API: Handle limit zero case in tests
